services:
  db:
    image: postgres:latest
    container_name: metrics_container
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: metrics_db
    ports:
      - "5432:5432"
  app:
    build: .
    container_name: metrics_app_container
    restart: unless-stopped
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql+psycopg://postgres:postgres@db:5432/metrics_db
    ports:
      - "8001:8001"
